import axios from 'axios';
import Head from 'next/head'
import styles from '../styles/Home.module.css'

function Home({ recipes }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Receta Random</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ¿No sabés que cocinar?
        </h1>

        <p className={styles.description}>
          El Tinder de recetas randoms
        </p>

        <div className={styles.grid}>
          {recipes && recipes.map(recipes => (
            <a href="#" key={recipes.id} className={styles.card}>
              <h3>{recipes.title}</h3>
              <p>{recipes.ingredients}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/martindevaluado"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with love by @martindevaluado
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const res = await axios.get('http://localhost:1337/recipes');
  const recipes = res.data

  return {
    props: {
      recipes,
    },
  }

}

export default Home